version: "3.7"

services:
  api-server:
    build:
      context: .
      target: develop
    ports:
      - 4321:80
    volumes:
      - .:/code
    depends_on:
      - api-server-mysql
    env_file:
      - .env.development
    command: npm run start:watch

  api-server-mysql:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - <you_path>:/var/lib/mysql
    env_file:
      - .env.development
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
